<?php

/**
 * Mapa operación AJAX (rqst.php `op`) → permiso requerido.
 *
 * Formatos:
 * - '' => solo sesión
 * - 'key' => un permiso
 * - ['a','b'] => OR (evitar para create/update)
 * - ['create'=>..,'update'=>..] => según id de la petición
 *
 * Política fail-closed: ops no listadas se deniegan en PermissionGate.
 *
 * @return array<string, mixed>
 */
return [
    'contactos_listar' => ['contactos.propio.view', 'contactos.todos.view'],
    'contactos_usuarios_filtro' => 'contactos.todos.view',
    'contactos_usuarios_asignar' => 'contactos.todos.manage',
    'contactos_guardar' => ['contactos.propio.manage', 'contactos.todos.manage'],
    'contactos_eliminar' => ['contactos.propio.manage', 'contactos.todos.manage'],

    'actoresget' => 'accion_unificada.config.actores.view',
    'acttualizarPerfil' => '',
    'actuaizarestadoproyecto' => 'proyectos.alcaldias.update',
    'actualizacionestrategicossave' => 'estrategicos.departamento.update',
    'actualizacioninformacionsave' => 'accion_unificada.config.actualizacion.create',
    'actualizar_estadoverificado' => 'compromisos.gobernador.update',
    'aprobar_proyecto_secretaria' => [
        'proyectos.alcaldias.planeacion.manage',
        'secretarias.proyectos.approve',
    ],
    'gestionar_proyecto_planeacion' => 'proyectos.alcaldias.planeacion.manage',
    'reabrir_proyecto_planeacion' => 'proyectos.alcaldias.planeacion.reopen',
    'dashboard_proyectos_planeacion_stats' => 'proyectos.alcaldias.planeacion.dashboard',
    'planeacion_usuarios_asignables' => 'proyectos.alcaldias.planeacion.assign',
    'planeacion_asignaciones_get' => [
        'proyectos.alcaldias.planeacion.assign',
        'proyectos.alcaldias.planeacion.detail',
        'proyectos.alcaldias.planeacion.view',
    ],
    'planeacion_asignar_usuarios' => 'proyectos.alcaldias.planeacion.assign',
    'planeacion_usuarios_filtro' => [
        'proyectos.alcaldias.planeacion.manage',
        'proyectos.alcaldias.planeacion.view_all',
        'proyectos.alcaldias.planeacion.view_all_alcaldia',
        'proyectos.alcaldias.planeacion.assign',
    ],
    'planeacion_informes_gestion' => 'proyectos.alcaldias.planeacion.informes',
    'editar_proyecto_rechazado' => [
        'proyectos.alcaldias.planeacion.create',
        'proyectos.alcaldias.planeacion.manage',
        'secretarias.proyectos.update',
        'secretarias.proyectos.create',
    ],
    'armadaget' => 'accion_unificada.municipios.view',
    'armadasave' => [
        'create' => 'accion_unificada.municipios.create',
        'update' => 'accion_unificada.municipios.update',
    ],
    'automatizar_delet_munic' => 'accion_unificada.config.factores_gobernacion.update',
    'automatizar_delet_vereda' => 'accion_unificada.config.factores_gobernacion.update',
    'bienes_get_resumen' => 'secretarias.administrativa.view',
    'bienesdelete' => 'secretarias.administrativa.update',
    'bienesget' => 'secretarias.administrativa.view',
    'bienessave' => [
        'create' => 'secretarias.administrativa.create',
        'update' => 'secretarias.administrativa.update',
    ],
    'brigadaget' => 'gestion_social.view',
    'brigadasave' => [
        'create' => 'gestion_social.create',
        'update' => 'gestion_social.update',
    ],
    'calcularPuntajeBrigada' => 'accion_unificada.departamento.view',
    'calcularPuntajeDepartamento' => 'accion_unificada.departamento.view',
    'ciudadget' => '',
    'configuracionpuntajesave' => [
        'create' => 'accion_unificada.config.puntajes.create',
        'update' => 'accion_unificada.config.puntajes.update',
    ],
    'configuracionpuntajesecretariasave' => [
        'create' => 'secretarias.config_puntajes.create',
        'update' => 'secretarias.config_puntajes.update',
    ],
    'data_map' => 'dashboard.mapa.view',
    'deletefiltros' => 'configuracion.sistema.update',
    'deleteingresoinformacion' => 'accion_unificada.config.informacion.update',
    'deleteproyecto' => 'proyectos.alcaldias.delete',
    'economicoget' => 'accion_unificada.municipios.view',
    'economicosave' => [
        'create' => 'accion_unificada.municipios.create',
        'update' => 'accion_unificada.municipios.update',
    ],
    'editarInformacion' => 'accion_unificada.config.informacion.update',
    'editarInformacionProyecto' => 'proyectos.alcaldias.update',
    'empresasdelete' => 'accion_unificada.empresas.delete',
    'empresassave' => [
        'create' => 'accion_unificada.empresas.create',
        'update' => 'accion_unificada.empresas.update',
    ],
    'empresafactordelete' => 'accion_unificada.empresa_factor.delete',
    'empresafactorget' => 'accion_unificada.empresa_factor.view',
    'empresafactorgetbyempresa' => 'accion_unificada.empresa_factor.view',
    'empresafactorgetbyfactor' => 'accion_unificada.empresa_factor.view',
    'empresafactorsave' => [
        'create' => 'accion_unificada.empresa_factor.create',
        'update' => 'accion_unificada.empresa_factor.update',
    ],
    'estrategiasave' => [
        'create' => 'configuracion.estrategias.create',
        'update' => 'configuracion.estrategias.update',
    ],
    'factoresInestabilidadSave' => [
        'create' => 'accion_unificada.config.factores_gobernacion.create',
        'update' => 'accion_unificada.config.factores_gobernacion.update',
    ],
    'factoresMassUpdateInestabilidad' => 'accion_unificada.config.factores_gobernacion.update',
    'factoresMassUpdateSecretaria' => 'secretarias.config_puntajes.update',
    'factoressave' => [
        'create' => 'accion_unificada.config.factores.create',
        'update' => 'accion_unificada.config.factores.update',
    ],
    'factor_actualizacion_detalle' => 'accion_unificada.municipios.view',
    'fetch_proyectos_por_estado' => 'secretarias.proyectos.view',
    'gestionarimagen_save' => 'configuracion.sistema.update',
    'getAllByMunicipio' => 'accion_unificada.municipios.view',
    'getArea' => '',
    'getByAlcaldia' => 'accion_unificada.config.actores.view',
    'getComponentesPorMunicipio' => 'secretarias.componentes.view',
    'getCompromisosFactores' => 'compromisos.gobernador.view',
    'getConsolidadoFactores' => 'secretarias.resumen.view',
    'getDataArcgisPae' => 'secretarias.pae.view',
    'getDatosRectorByInstitucionYSede' => 'secretarias.pae.view',
    'getDependenciasRpc' => 'secretarias.rpc.view',
    'getEstadisticasLogsApiRpc' => 'secretarias.rpc.logs.view',
    'getEstadisticasLogsPaeArcgis' => 'secretarias.pae.logs.view',
    'getFactores' => '',
    'getFactoresDelete' => 'accion_unificada.config.factores.update',
    'getFactoresInestabilidad' => 'accion_unificada.config.factores_gobernacion.view',
    'getFactoresInestabilidadDelete' => 'accion_unificada.config.factores_gobernacion.update',
    'getFactoresInestabilidadList' => 'accion_unificada.config.factores_gobernacion.view',
    'getFactoresPorMunicipiosByPilarIdPorColores' => 'accion_unificada.municipios.view',
    'getFactoresVereda' => 'accion_unificada.veredas.view',
    'getGraficoTemaInteres' => 'policia.graficos.view',
    'getInstitucionesByCodigoMunicipio' => 'secretarias.pae.view',
    'getLogDetalleApiRpc' => 'secretarias.rpc.logs.view',
    'getLogDetallePaeArcgis' => 'secretarias.pae.logs.view',
    'getLogsApiRpc' => 'secretarias.rpc.logs.view',
    'getLogsPaeArcgis' => 'secretarias.pae.logs.view',
    'getMunicipiosArcgis' => 'secretarias.pae.view',
    'getPersonasByFiltroId' => 'configuracion.sistema.view',
    'getPilar' => '',
    'getPoblacionImpactadaPorMunicipio' => 'gestion_social.view',
    'getPoblacionImpactadaPorMunicipioAspas' => 'gestion_social.aspas.view',
    'getProyectosRpc' => 'secretarias.rpc.view',
    'getPuntaje' => 'accion_unificada.config.puntajes.view',
    'getPuntajeSecretaria' => 'secretarias.config_puntajes.view',
    'getPuntajesInestabilidad' => 'accion_unificada.veredas_criticas.view',
    'getResumenMunicipiosPae' => 'secretarias.pae.view',
    'getResumenProyectosRpc' => 'secretarias.rpc.view',
    'getSedeEducativa' => 'secretarias.pae.view',
    'getSedeEducativaByCodMunicipio' => 'secretarias.pae.view',
    'getSedesInformacionMapaPae' => 'secretarias.pae.view',
    'getSoloVisitasPorMes' => 'visitas.gobernador.view',
    'getSoloVisitasPorMesAlcalde' => 'visitas.alcalde.view',
    'getTotalDetalladoTipoActividad' => 'gestion_social.view',
    'getTotalEjecucionSecretaria' => 'secretarias.proyectos.view',
    'getTotalVisitasPorMunicipiosAlcalde' => 'visitas.alcalde.view',
    'getTotalVisitasPorProvincias' => 'visitas.gobernador.view',
    'getTotalVisitasPorVeredasAlcalde' => 'visitas.alcalde.view',
    'getVeredasByMunicipioId' => '',
    'getVeredasCriticas' => 'accion_unificada.veredas_criticas.view',
    'get_consolidado_departamental' => 'accion_unificada.departamento.view',
    'get_consolidado_inestabilidad_departamental' => 'accion_unificada.departamento.view',
    'get_consolidado_por_municipio' => 'accion_unificada.municipios.view',
    'get_estadisticas_bd' => 'accion_unificada.estadisticas_bd.view',
    'get_graficos' => 'policia.graficos.view',
    'get_inestabilidad_mapa' => 'accion_unificada.departamento.view',
    'get_munic_x_batallon' => 'accion_unificada.departamento.view',
    'get_munic_x_brigadas' => 'accion_unificada.departamento.view',
    'get_solo_munic_x_batallon' => 'accion_unificada.departamento.view',
    'get_solo_vereda_x_batallon' => 'accion_unificada.departamento.view',
    'get_veredas_by_nivel' => 'accion_unificada.veredas.view',
    'get_veredas_criticas' => 'accion_unificada.veredas_criticas.view',
    'get_veredas_criticas_data_basica' => 'accion_unificada.veredas_criticas.view',
    'get_veredas_criticas_seleccion' => 'accion_unificada.veredas_criticas.view',
    'get_veredas_sin_desplazamiento' => 'accion_unificada.veredas.view',
    'get_veredas_sin_desplazamiento_brigadas' => 'accion_unificada.veredas.view',
    'getestrategia' => '',
    'getfactores' => 'accion_unificada.factores_listado.view',
    'getfactoresbymunic' => 'accion_unificada.municipios.view',
    'getfactoresbymunicNUEVO' => 'accion_unificada.municipios.view',
    'getfactoresbymunicVersion2022' => 'accion_unificada.municipios.view',
    'getlinea' => '',
    'getmapafactores' => 'accion_unificada.factores_listado.view',
    'getmapainformacionalcaldia' => 'accion_unificada.municipios.view',
    'getmapainformacionsecretaria' => 'accion_unificada.municipios.view',
    'getmapapilaresbymunicipioId' => 'accion_unificada.municipios.view',
    'getprensa' => 'prensa.view',
    'getpromediops2025porsecretaria' => 'secretarias.proyectos.view',
    'getresultadosmunicipio' => 'accion_unificada.municipios.view',
    'getresultadosvereda' => 'accion_unificada.veredas.view',
    'gettic' => 'secretarias.tic.view',
    'gettotalvisitaspormesmunicipio' => 'visitas.gobernador.view',
    'gettotalvisitasporprovincia' => 'visitas.gobernador.view',
    'getveredasbycolor' => 'accion_unificada.veredas.view',
    'getveredasbycolor_depart' => 'accion_unificada.departamento.view',
    'getveredasbycolor_depart2021' => 'accion_unificada.departamento.view',
    'getveredasbycolor_munic' => 'accion_unificada.municipios.view',
    'getveredasbycolor_munic2021' => 'accion_unificada.municipios.view',
    'getveredasbycolorbatallon' => 'accion_unificada.veredas.view',
    'getveredasbycolorbatallon2021' => 'accion_unificada.veredas.view',
    'getveredasbycolorbrigada2021' => 'accion_unificada.veredas.view',
    'graficasPorFatoresVeredasPorColor' => 'accion_unificada.veredas.view',
    'guardarCompromiso' => 'compromisos.gobernador.create',
    'guardar_anotacion_secretaria' => 'secretarias.proyectos.update',
    'hacienda_get_consolidado' => 'secretarias.hacienda.view',
    'hacienda_save' => [
        'create' => 'secretarias.hacienda.create',
        'update' => 'secretarias.hacienda.update',
    ],
    'hacienda_update' => 'secretarias.hacienda.update',
    'ingresoactores_save' => [
        'create' => 'accion_unificada.config.actores.create',
        'update' => 'accion_unificada.config.actores.update',
    ],
    'ingresoactoresreg_save' => [
        'create' => 'accion_unificada.config.actores.create',
        'update' => 'accion_unificada.config.actores.update',
    ],
    'ingresoestrategicossave' => [
        'create' => 'estrategicos.departamento.create',
        'update' => 'estrategicos.departamento.update',
    ],
    'ingresoinformacionsave' => [
        'create' => 'accion_unificada.config.informacion.create',
        'update' => 'accion_unificada.config.informacion.update',
    ],
    'ingresoproyectos4_save' => 'proyectos.alcaldias.create',
    'ingresoproyectos_save' => 'proyectos.alcaldias.create',
    'ingresoproyectosmin_save' => 'proyectos.alcaldias.create',
    'ingresovotaciones_save' => [
        'create' => 'accion_unificada.municipios.create',
        'update' => 'accion_unificada.municipios.update',
    ],
    'inversion_delete' => 'interior.contratos.update',
    'inversion_get' => 'interior.contratos.view',
    'inversion_list' => 'interior.contratos.view',
    'inversion_save' => 'interior.contratos.create',
    'inversion_update' => 'interior.contratos.update',
    'leerproyectoyactualizarestado' => 'proyectos.alcaldias.update',
    'limpiarLogsApiRpc' => 'secretarias.rpc.logs.manage',
    'limpiarLogsPaeArcgis' => 'secretarias.pae.logs.manage',
    'ministerioget' => '',
    'ministeriosave' => [
        'create' => 'configuracion.ministerios.create',
        'update' => 'configuracion.ministerios.update',
    ],
    'municipiosbyprovincia' => '',
    'obtener_detalles_proyecto' => [
        'proyectos.alcaldias.planeacion.detail',
        'proyectos.alcaldias.planeacion.view',
        'secretarias.proyectos.view',
    ],
    'obtener_logs_proyecto' => [
        'proyectos.alcaldias.planeacion.detail',
        'proyectos.alcaldias.planeacion.view',
        'secretarias.proyectos.view',
    ],
    'obtener_registros_existentes' => 'accion_unificada.config.actualizacion.view',
    'operatividadeget' => 'policia.informes.view',
    'operatividadsave' => 'policia.informes.view',
    'operatividadupdate' => 'policia.informes.view',
    'pms_candidatoget' => 'configuracion.sistema.view',
    'pms_candidatosave' => 'configuracion.sistema.update',
    'pms_compromisoget' => 'compromisos.gobernador.view',
    'pms_compromisos' => [
        'create' => 'compromisos.gobernador.create',
        'update' => 'compromisos.gobernador.update',
    ],
    'pms_confsave' => 'configuracion.sistema.update',
    'pms_cuentaprovincia' => 'visitas.gobernador.view',
    'pms_cuentavisita' => 'visitas.gobernador.view',
    'pms_deleteimage' => 'configuracion.sistema.update',
    'pms_desarrollo_filtar_secretaria' => 'plan_desarrollo.view',
    'pms_desarrollo_get' => 'plan_desarrollo.view',
    'pms_desarrollo_save' => [
        'create' => 'plan_desarrollo.create',
        'update' => 'plan_desarrollo.update',
    ],
    'pms_getconf' => 'configuracion.sistema.view',
    'pms_getproyerctos' => 'proyectos.alcaldias.view',
    'pms_getproyerctos4' => 'proyectos.alcaldias.view',
    'pms_getproyerctosmin' => 'proyectos.alcaldias.view',
    'pms_getvotacion' => 'accion_unificada.municipios.view',
    'pms_lideravailable' => 'configuracion.sistema.view',
    'pms_liderget' => 'configuracion.sistema.view',
    'pms_lidersave' => 'configuracion.sistema.update',
    'pms_showimage' => 'configuracion.sistema.view',
    'pms_usravailable' => 'configuracion.usuarios.create',
    'pms_usrdelete' => 'configuracion.usuarios.update',
    'pms_usrenable' => 'configuracion.usuarios.update',
    'pms_usrget' => 'configuracion.usuarios.view',
    'pms_usrlogin' => '',
    'pms_usrpermission' => 'configuracion.usuarios.manage',
    'pms_usrsave' => [
        'create' => 'configuracion.usuarios.create',
        'update' => 'configuracion.usuarios.update',
    ],
    'pms_usrsavepermission' => 'configuracion.usuarios.manage',
    'pms_visitamunget' => 'visitas.gobernador.view',
    'pms_visitas' => [
        'create' => 'visitas.gobernador.create',
        'update' => 'visitas.gobernador.update',
    ],
    'pms_visitasget' => 'visitas.gobernador.view',
    'pms_votacionupdate' => 'accion_unificada.municipios.update',
    'proyectos_alcaldias_update' => 'proyectos.alcaldias.update',
    'proyectos_secretaria_save' => [
        'proyectos.alcaldias.planeacion.create',
        'secretarias.proyectos.create',
    ],
    'proyectosalcaldias_delete' => 'proyectos.alcaldias.delete',
    'proyectosalcaldias_getall' => 'proyectos.alcaldias.view',
    'proyectosalcaldias_inversion_secretaria' => 'proyectos.alcaldias.view',
    'proyectosalcaldias_inversion_total' => 'proyectos.alcaldias.view',
    'proyectosalcaldias_observaciones' => 'proyectos.alcaldias.view',
    'proyectosalcaldias_provincias' => 'proyectos.alcaldias.view',
    'proyectosalcaldias_save' => [
        'create' => 'proyectos.alcaldias.create',
        'update' => 'proyectos.alcaldias.update',
    ],
    'rechazar_proyecto_secretaria' => [
        'proyectos.alcaldias.planeacion.manage',
        'secretarias.proyectos.approve',
    ],
    'reportefeget' => 'accion_unificada.informes.view',
    'reportefesave' => 'accion_unificada.informes.view',
    'roledelete' => 'configuracion.roles.manage',
    'roleget' => 'configuracion.roles.view',
    'rolepermissionscatalog' => 'configuracion.roles.view',
    'rolesave' => 'configuracion.roles.manage',
    'roleslist' => 'configuracion.roles.view',
    'savearea' => [
        'create' => 'accion_unificada.config.areas.create',
        'update' => 'accion_unificada.config.areas.update',
    ],
    'savefiltros' => 'configuracion.sistema.update',
    'saveinfo' => 'accion_unificada.config.informacion.create',
    'savelinea' => [
        'create' => 'configuracion.lineas.create',
        'update' => 'configuracion.lineas.update',
    ],
    'savepaedan' => [
        'create' => 'secretarias.pae.create',
        'update' => 'secretarias.pae.update',
    ],
    'saveprensa' => [
        'create' => 'prensa.create',
        'update' => 'prensa.update',
    ],
    'savetic' => [
        'create' => 'secretarias.tic.create',
        'update' => 'secretarias.tic.update',
    ],
    'secretariaget' => '',
    'secretariasave' => [
        'create' => 'configuracion.secretarias.create',
        'update' => 'configuracion.secretarias.update',
    ],
    'secretariasmunicipalespormunicipio' => [
        'secretarias.municipales.view',
        'proyectos.alcaldias.planeacion.view',
        'proyectos.alcaldias.create',
        'proyectos.alcaldias.view',
        'secretarias.proyectos.create',
        'secretarias.proyectos.view',
        'compromisos.alcalde.view',
    ],
    'metas_plan_desarrollo_por_municipio' => [
        'proyectos.alcaldias.planeacion.view',
        'proyectos.alcaldias.create',
        'proyectos.alcaldias.view',
        'secretarias.proyectos.create',
        'secretarias.proyectos.view',
        'plan_desarrollo.view',
        'secretarias.municipales.view',
    ],
    'sedeEducativasConProblemas' => 'secretarias.pae.view',
    'socialessave' => [
        'create' => 'gestion_social.create',
        'update' => 'gestion_social.update',
    ],
    'socialget' => 'gestion_social.view',
    'spi_acciong_delete' => 'configuracion.acciones_gestion.delete',
    'spi_acciong_get' => '',
    'spi_acciong_save' => [
        'create' => 'configuracion.acciones_gestion.create',
        'update' => 'configuracion.acciones_gestion.update',
    ],
    'spi_actores_get' => 'accion_unificada.config.actores.view',
    'spi_actores_save' => [
        'create' => 'accion_unificada.config.actores.create',
        'update' => 'accion_unificada.config.actores.update',
    ],
    'spi_visitas_save' => [
        'create' => 'gestion_social.create',
        'update' => 'gestion_social.update',
    ],
    'spi_visitas_save_aspas' => [
        'create' => 'gestion_social.aspas.create',
        'update' => 'gestion_social.aspas.update',
    ],
    'spi_visitasg_get' => 'gestion_social.view',
    'spi_visitasg_get_aspas' => 'gestion_social.aspas.view',
    'spi_visitasg_save' => [
        'create' => 'gestion_social.create',
        'update' => 'gestion_social.update',
    ],
    'upd_descrip_vereda' => 'accion_unificada.veredas.update',
    'update_avance' => 'accion_unificada.avances.update',
    'updateinfo' => 'accion_unificada.config.actualizacion.create',
    'vereda_get_by_id' => 'configuracion.veredas.manage',
    'vereda_preview_codigo' => 'configuracion.veredas.manage',
    'vereda_save' => 'configuracion.veredas.manage',
    'vereda_update' => 'configuracion.veredas.manage',
    'veredaget' => '',
    'veredas_get_admin' => 'configuracion.veredas.manage',
    'veredas_municipios_santander' => 'configuracion.veredas.manage',
];
